### PR TITLE
Force ALE_USER_ID field to SECURITY_DESCRIPTOR type

### LINKED ISSUE #12: Incorrect Type Reported by FWPM_CONDITION_ALE_USER_ID
For some reason, the WFP reports the User ID field as taking a `TOKEN_ACCESS_INFORMATION` as the value type. However, the [documentation](https://docs.microsoft.com/en-us/windows/win32/fwp/filtering-condition-identifiers-#FWPM_CONDITION_ALE_USER_ID) indicates that it takes a `SECURITY_DESCRIPTOR` type.

Anecdotally, dumping existing WFP rules with `netsh wfp show filters` does show existing/default filters using the `SECURITY_DESCRIPTOR` type for `ALE_USER_ID` fields.

Any idea why there is a mismatch here? It seems to be coming directly from the Win32 layer enumeration methods and not from your module, but I'm interested in any insight you may have. I've been able to work around this by forcing the type for this specific field to `typeSecurityDescriptor` in `func fieldType(f *fwpmField0) (reflect.Type, error)`, but that seemed rather hacky.

### PR DESCRIPTION
**Pull request by calebstewart**
Based on the documentation, the FWPM_CONDITION_ALE_USER_ID field should
have the type FWP_SECURITY_DESCRIPTOR TYPE. This fix forces this type
because WFP is incorrectly reporting TOKEN_ACCESS_INFORMATION_TYPE
instead.

[Relevant Documentation](https://docs.microsoft.com/en-us/windows/win32/fwp/filtering-condition-identifiers-#FWPM_CONDITION_ALE_USER_ID).

I believe I got the Sign-Off stuff right this time, but I've never used it before. :eye: :nose: :eye: 

This would fix #12.

### CODE REVIEW

**Review by danderson — COMMENTED** [review]
Hmm. I'm having flashbacks to writing this code and discovering that security descriptors and token access information structs don't match up in the write and read direction... I think because a TokenAccessInformation is a superset of what SecurityDescriptor contains? I could never keep it straight, or get good information on how they mix and match.

Does this field decode to correct values with this patch? This looks reasonable at a glance, but I'm worried that I don't remember all the subtleties of this API.

**Comment by danderson** [comment]
Oh, and you need to fix up firewall_test.go, which has a test that enumerates an ALE layer and expects specific types to come back.

**Comment by danderson** [comment]
Looking at that test... Should FieldALERemoteUserID also be changed? It's currently also a TokenAccessInformation in the code.

**Comment by calebstewart** [comment]
> Does this field decode to correct values with this patch?
I'll do some more testing in the other direction. I was focused on trying to create new rules, but that's a good point on the deserialization perspective.

> Looking at that test... Should FieldALERemoteUserID also be changed? It's currently also a TokenAccessInformation in the code.
According to the docs linked above, both `FieldALERemoteUserID` and `FieldALERemoteMachineID` should use the `SECURITY_DESCRIPTOR` type. I do find it odd that when enumerating the existing layers, it returns a `TOKEN_ACCESS_INFORMATION` type though. The documentation is pretty vague about what exactly that is, and doesn't even document any fields that use that type, sadly.

Would you like me to make the changes (I.e. force the field type to `typeSecurityDescriptor`) for those fields as well? The discrepancy between the enumerated layers and the documentation makes me a little uneasy about this patch, to be honest. For creating new rules, I can say right now that it works for `FieldALEUserID`. As I said above, I'll verify that deserialization/reading of rules works with this as well and get back to you.

**Comment by calebstewart** [comment]
I apologize for the delay. I've made some changes here. Namely, I've been testing with forcing all fields that were previously marked as `TokenAccessInformation` to `SecurityDescriptor` types instead of just the one user ID field. This matches closer to what I understand from the MSDN documentation. I've also updated the firewall tests to ensure they match/pass. Lastly, I did some testing with `netsh wfp show filters`, and can say anecdotally that the filters appear to match that output when queried through `wfpcli`.

I understand this is a non-trivial change, so I'm open to more discussion on the topic, but this appears to be working well for me at least.

**Comment by itsmurugappan** [comment]
@calebstewart I was trying to test this patch, was hitting this error when I tried to send a security descriptor to add a rule.
"The parameter is incorrect". I built the security descriptor from string using windows.SecurityDescriptorFromString(). Am I missing something?

**Comment by itsmurugappan** [comment]
I wasnt building the descriptor correctly. On successful creation the rule creation/retrieve works with this patch

**Comment by calebstewart** [comment]
@danderson is there anything currently preventing this from being merged? I understand there was some ambiguity between the reported types at runtime vs the documentation, but all testing I've done has shown this is working and valid and matching all documentation I can find on MSDN. If there's any other research, testing or discussion needed, I'm happy to do it. However, I would also prefer to get this PR closed soon.

I've been using these changes internally for a while now with no issues, and would love to stop maintaining the tracking status of my internal branch. I did just realize there was a small error from `staticcheck` about the now unused `typeTokenAccessInformation` variable, so I've fixed that in case it was a blocker.

Thanks for your time!

**Comment by abennett** [comment]
I'm not giving up on you, PR #14!

**Comment by abennett** [comment]
@bradfitz, I know you're out there somewhere doing good stuff. Are you able to help move this along? 🙏

**Comment by bradfitz** [comment]
No clue. I defer to @danderson. I don't know any of this stuff.

**Comment by danderson** [comment]
Sorry for the delays. Kept meaning to come back to this and have a deep think about this, because I'm unfamiliar enough with the windows APIs that I have to page it all back in every time I need to think about changing anything. But as bradfitz pointed out to me, you already did deep research on this, and it's not changing any of the subtle/scary bits of the library (the unsafe pointer trickery), so... LGTM, and thank you!

**Comment by abennett** [comment]
You are both champs! Have a great week!

**Pull request merged**
